image: docker.io/hugomods/hugo:std-git-0.140.2

pages:
  script:
    # Clone du moteur
    - git clone https://gitlab.com/hamlet580-group/hamlet580-project-engine.git

    # Préparation des dossiers Hugo
    - mkdir -p themes
    - mkdir -p layouts
    - mkdir -p static

    # Injection du moteur
    - cp -r hamlet580-project-engine/themes/* themes/
    - cp -r hamlet580-project-engine/layouts/* layouts/
    - cp -r hamlet580-project-engine/static/* static/

    # Build
    - hugo

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH