backend:
  name: gitlab
  repo: ${REPO}
  branch: main
  auth_type: pkce
  app_id: ef799dda35b19c5350294ced637400ca898c064e0bee7434df1c1e4251987769
media_folder: static/fichiers
public_folder: /fichiers
collections:
  - name: 'posts'
    label: 'Articles'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    media_folder: "static/fichiers/articles/{{slug}}"
    public_folder: "/fichiers/articles/{{slug}}"
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'page'
    label: 'Pages'
    folder: 'content/page'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    media_folder: "static/fichiers/pages/{{slug}}"
    public_folder: "/fichiers/pages/{{slug}}"
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
locale: fr